# Generated by Django 2.2.7 on 2019-11-19 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchsource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('skill', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
