# Generated by Django 2.2.7 on 2019-11-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchsource', '0002_userskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskill',
            name='skill',
            field=models.TextField(blank=True),
        ),
    ]
